### ISSUE TITLE
Add zoom to Ajax URL

### ISSUE THREAD

**Issue by BaDu-HSN** [Dominique92/Leaflet.GeoJSON.Ajax#2]
The AJAX URL is constructed using the URL supplied in the options and a bbox parameters are added if set in the options.
A nice addition would be to add a possibility of a zoom parameter to the URL. I've modified the code for my project as follows:
After line 76 of GeoJSON.Ajax.js add the following code:
`
// BaDu-HSN: extends Add zoom param if necessary

		if (this.options.zoom && this._map)
			argsGeoJSON.zoom = this._map.getZoom();
`

**Comment by Dominique92** [comment]
Done. Great option !
Not necessary each time but can be usefull for some ajax server calculation.
Thank you very much for the idea.
